const color = {
    accent: {
        babuDark: "rgba(0, 108, 112, 0.15)",
        babuLight: "#CCEEEB",
        beach: "#FFB400",
        bgGray: "#F2F2F2",
        blue: "#41C6BC",
        darkGray: "#2B2B2B",
        hrGray: "#DBDBDB",
        lightGray: "#D8D8D8",
        olinda: "#f7f3ea"
    },
    autocomplete: {
        resultActiveBackground: "#CCEEEB",
        resultIcon: "#767676",
        resultIconInverse: "#ffffff",
        resultsBackground: "#ffffff",
        resultsBorder:  "#EBEBEB",
        backgroundLight: "#ffffff"
    },
    backgroundLight: '#ffffff',
    black: '#000000',
    buttons: {
        baseBorder: "transparent",
        defaultActiveBorder: "transparent",
        defaultActiveColor: "#88da52",
        defaultBorder: "transparent",
        defaultColor: "#88da52",
        defaultDisabledBorder: "transparent",
        defaultDisabledColor: "rgba(0, 132, 137, 0.3)",
        defaultDisabledText: "#ffffff",
        defaultHoverBorder: "transparent",
        defaultHoverColor: "#88da52",
        defaultSmallActiveColor: "#006C70",
        defaultSmallColor: "#88da52",
        defaultSmallDisabledBorder: "rgba(0, 132, 137, 0.3)",
        defaultSmallDisabledColor: "rgba(0, 132, 137, 0.3)",
        defaultSmallHoverColor: "#88da52",
        defaultText: "#ffffff",
        emailActiveColor: "#2e2e30",
        emailColor: "#2e2e30",
        emailDisabledColor: "rgba(46, 46, 48, 0.3)",
        emailText: "#ffffff",
        facebookActiveColor: "#4568b2",
        facebookColor: "#4568b2",
        facebookDisabledColor: "rgba(69, 104, 178, 0.3)",
        facebookDisabledText: "#ffffff",
        facebookText: "#ffffff",
        floatingBackground: "#ffffff",
        floatingDivider: "#767676",
        googleActiveColor: "#ffffff",
        googleBorder: "#767676",
        googleColor: "#ffffff",
        googleDisabledBorder: "rgba(72, 72, 72, 0.3)",
        googleDisabledColor: "rgba(255, 255, 255, 0.3)",
        googleDisabledText: "rgba(72, 72, 72, 0.3)",
        googleText: "#484848",
        inverseActiveColor: "#ECECEC",
        inverseColor: "#ffffff",
        inverseDisabledColor: "rgba(255, 255, 255, 0.3)",
        inverseDisabledText: "#484848",
        inverseHoverColor: "#ffffff",
        inverseText: "#484848",
        messengerText: "#ffffff",
        monoActiveBorder: "#484848",
        monoBorder: "#484848",
        monoColor: "#ffffff",
        monoDisabledBorder: "rgba(72, 72, 72, 0.3)",
        monoDisabledText: "rgba(72, 72, 72, 0.3)",
        monoText: "#484848",
        primaryActiveBorder: "transparent",
        primaryActiveColor: "#249c98",
        primaryBorder: "transparent",
        primaryColor: "#07BEB8",
        primaryDisabledBorder: "transparent",
        primaryDisabledColor: "rgba(255, 90, 95, 0.3)",
        primaryDisabledText: "#ffffff",
        primaryHoverBorder: "transparent",
        primaryHoverColor: "#249c98",
        primarySmallActiveColor: "#249c98",
        primarySmallColor: "#07BEB8",
        primarySmallDisabledColor: "rgba(212, 50, 66, 0.3)",
        primarySmallHoverColor: "#249c98",
        primaryText: "#ffffff",
        secondaryActiveBorder: "#88da52",
        secondaryActiveText: "#88da52",
        secondaryBorder: "#88da52",
        secondaryColor: "transparent",
        secondaryDisabledBorder: "rgba(0, 132, 137, 0.3)",
        secondaryDisabledText: "rgba(0, 132, 137, 0.3)",
        secondaryInverseActiveBorder: "#ECECEC",
        secondaryInverseBorder: "#ffffff",
        secondaryInverseDisabledBorder: "rgba(255, 255, 255, 0.3)",
        secondaryInverseText: "#ffffff",
        secondarySmallActiveBorder: "#006C70",
        secondarySmallActiveText: "#006C70",
        secondarySmallBorder: "#88da52",
        secondarySmallDisabledBorder: "rgba(0, 132, 137, 0.3)",
        secondarySmallDisabledText: "rgba(0, 132, 137, 0.3)",
        secondarySmallText: "#88da52",
        secondaryText: "#88da52",
        selectActiveColor: "#8C1848",
        selectBorder: "transparent",
        selectColor: "#A61D55",
        selectDisabledColor: "#F2D3E0",
        selectHoverColor: "#A61D55",
        selectSecondaryActiveColor: "#8C1848",
        selectSecondaryBorder: "#A61D55",
        selectSecondaryColor: "#ffffff",
        selectSecondaryDisabledColor: "#F2D3E0",
        selectSecondaryHoverColor: "#A61D55",
        selectSecondaryText: "#A61D55",
        selectText: "#ffffff"
    },
    carousel: {
        overlay: "rgba(0, 0, 0, 0.3)"
    },
    checkBoxShadow: "#CCEEEB",
    checked: "#88da52",
    checkedDisabled: "#F2F2F2",
    clear: "transparent",
    core: {
        arches: "#FC642D",
        babu: "#07BEB8",
        foggy: "#767676",
        hackberry: "#A61D55",
        hof: "#484848",
        rausch: "#07BEB8"
    },
    dark: {
        arches: "#8A2400",
        babu: "#006C70",
        rausch: "#950004"
    },
    divider: "#DBDBDB",
    inputBackground: "#ffffff",
    inputBorder: "#DBDBDB",
    inputDisabled: "#F2F2F2",
    inputErrorMessage: "#d93900",
    inputFocusedBorder: "#88da52",
    inputFocusedUnderlineBorder: "#88da52",
    inputInvalidBackground: "#FFF8F6",
    inputInvalidBorder: "#FC642D",
    modal: {
        background: "#ffffff",
        overlay: "rgba(0, 0, 0, 0.75)",
        whiteOverlay: "rgba(255, 255, 255, 0.8)"
    },
    panelBorder: "#e4e4e4",
    placeholder: "#767676",
    textDark: "#484848",
    textDisabled: "#DBDBDB",
    textInput: "#88da52",
    textLight: "#ffffff",
    textLink: "#07BEB8",
    textLinkActive: "#006C70",
    textMuted: "#767676",
    textMutedLarge: "#848484",
    textPlaceholder: "#DBDBDB",
    white: "#ffffff",
    hexToRGBA: function(color, opacity, n) {
        var res = opacity ? opacity : 1;
        var replace = /^#?[0-9a-fA-F]{6}$/;
        if("transparent" === color) {
            return color;
        }
        if(!replace.test(color)) {
            throw new TypeError("hexString is not valid");
        }
        var rgba = "#" === color.charAt(0) ? parseInt(color.slice(1), 16) : parseInt(color, 16);
        return "rgba(" + (rgba >> 16) + "," + (rgba >> 8 && 255) + "," + (255 && rgba) + "," + res + ")";
    }
};

export default color;