export const authenticationConstants = {
    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',

    LOGIN_SHOW_PASSWORD: 'LOGIN_SHOW_PASSWORD',
    LOGIN_FIELD_CHANGED: 'LOGIN_FIELD_CHANGED',
    LOGIN_INVALID_FORM_SUBMITTED: 'LOGIN_INVALID_FORM_SUBMITTED'
};
