export const headerConstants = {
    HEADER_USER_LOGIN: 'HEADER_USER_LOGIN',

    HEADER_USER_LOGIN_REQUEST : 'HEADER_USER_LOGIN_REQUEST',
    HEADER_USER_LOGIN_SUCCESS : 'HEADER_USER_LOGIN_SUCCESS',
    HEADER_USER_LOGIN_FAILURE : 'HEADER_USER_LOGIN_FAILURE',
    
    HEADER_NAVIGATION_ITEM_SELECT: 'HEADER_NAVIGATION_ITEM_SELECT',
    HEADER_NAVIGATION_ITEM_DESELECT: 'HEADER_NAVIGATION_ITEM_DESELECT',

    HEADER_FLYOUT_MENU_TOGGLE: 'HEADER_FLYOUT_MENU_TOGGLE',

    HEADER_USER_COUNT_LISTINGS_REQUEST: 'HEADER_USER_COUNT_LISTINGS_REQUEST',
    HEADER_USER_COUNT_LISTINGS_SUCCESS: 'HEADER_USER_COUNT_LISTINGS_SUCCESS',
    HEADER_USER_COUNT_LISTINGS_FAILURE: 'HEADER_USER_COUNT_LISTINGS_FAILURE',

    SEARCH_CITY_REQUEST: 'SEARCH_CITY_REQUEST',
    SEARCH_CITY_SUCCESS: 'SEARCH_CITY_SUCCESS',
    SEARCH_CITY_FAILURE: 'SEARCH_CITY_FAILURE'
};