export const meAgencyConstants = {
    ME_AGENCY_REQUEST: 'ME_AGENCY_REQUEST',
    ME_AGENCY_SUCCESS: 'ME_AGENCY_SUCCESS',
    ME_AGENCY_FAILURE: 'ME_AGENCY_FAILURE',

    ME_AGENCY_INSERT_REQUEST: 'ME_AGENCY_INSERT_REQUEST',
    ME_AGENCY_INSERT_SUCCESS: 'ME_AGENCY_INSERT_SUCCESS',
    ME_AGENCY_INSERT_FAILURE: 'ME_AGENCY_INSERT_FAILURE',

    ME_AGENCY_UPDATE_REQUEST: 'ME_AGENCY_UPDATE_REQUEST',
    ME_AGENCY_UPDATE_SUCCESS: 'ME_AGENCY_UPDATE_SUCCESS',
    ME_AGENCY_UPDATE_FAILURE: 'ME_AGENCY_UPDATE_FAILURE',

    ME_AGENCY_FIELD_CHANGED: 'ME_AGENCY_FIELD_CHANGED',

    ME_AGENCY_VALID_FORM_SUBMITTED: 'ME_AGENCY_VALID_FORM_SUBMITTED',
    ME_AGENCY_INVALID_FORM_SUBMITTED: 'ME_AGENCY_INVALID_FORM_SUBMITTED'
};
