export const meListingConstants = {
    ME_LISTING_HYDRATE: 'ME_LISTING_HYDRATE',

    ME_LISTING_REQUEST: 'ME_LISTING_REQUEST',
    ME_LISTING_SUCCESS: 'ME_LISTING_SUCCESS',
    ME_LISTING_FAILURE: 'ME_LISTING_FAILURE',

    ME_LISTINGS_REQUEST: 'ME_LISTINGS_REQUEST',
    ME_LISTINGS_SUCCESS: 'ME_LISTINGS_SUCCESS',
    ME_LISTINGS_FAILURE: 'ME_LISTINGS_FAILURE',

    ME_LISTING_INSERT_REQUEST: 'ME_LISTING_INSERT_REQUEST',
    ME_LISTING_INSERT_SUCCESS: 'ME_LISTING_INSERT_SUCCESS',
    ME_LISTING_INSERT_FAILURE: 'ME_LISTING_INSERT_FAILURE',

    ME_LISTING_UPDATE_REQUEST: 'ME_LISTING_UPDATE_REQUEST',
    ME_LISTING_UPDATE_SUCCESS: 'ME_LISTING_UPDATE_SUCCESS',
    ME_LISTING_UPDATE_FAILURE: 'ME_LISTING_UPDATE_FAILURE',

    ME_LISTING_UPDATE_OWNER_REQUEST: 'ME_LISTING_UPDATE_OWNER_REQUEST',
    ME_LISTING_UPDATE_OWNER_SUCCESS: 'ME_LISTING_UPDATE_OWNER_SUCCESS',
    ME_LISTING_UPDATE_OWNER_FAILURE: 'ME_LISTING_UPDATE_OWNER_FAILURE',

    ME_LISTING_UPDATE_TYPE_REQUEST: 'ME_LISTING_UPDATE_TYPE_REQUEST',
    ME_LISTING_UPDATE_TYPE_SUCCESS: 'ME_LISTING_UPDATE_TYPE_SUCCESS',
    ME_LISTING_UPDATE_TYPE_FAILURE: 'ME_LISTING_UPDATE_TYPE_FAILURE',

    ME_LISTING_UPDATE_PLACE_REQUEST: 'ME_LISTING_UPDATE_PLACE_REQUEST',
    ME_LISTING_UPDATE_PLACE_SUCCESS: 'ME_LISTING_UPDATE_PLACE_SUCCESS',
    ME_LISTING_UPDATE_PLACE_FAILURE: 'ME_LISTING_UPDATE_PLACE_FAILURE',

    ME_LISTING_UPDATE_DETAILS_REQUEST: 'ME_LISTING_UPDATE_DETAILS_REQUEST',
    ME_LISTING_UPDATE_DETAILS_SUCCESS: 'ME_LISTING_UPDATE_DETAILS_SUCCESS',
    ME_LISTING_UPDATE_DETAILS_FAILURE: 'ME_LISTING_UPDATE_DETAILS_FAILURE',

    ME_LISTING_UPDATE_COMFORTS_REQUEST: 'ME_LISTING_UPDATE_COMFORTS_REQUEST',
    ME_LISTING_UPDATE_COMFORTS_SUCCESS: 'ME_LISTING_UPDATE_COMFORTS_SUCCESS',
    ME_LISTING_UPDATE_COMFORTS_FAILURE: 'ME_LISTING_UPDATE_COMFORTS_FAILURE',

    ME_LISTING_DELETE_REQUEST: 'ME_LISTING_DELETE_REQUEST',
    ME_LISTING_DELETE_SUCCESS: 'ME_LISTING_DELETE_SUCCESS',
    ME_LISTING_DELETE_FAILURE: 'ME_LISTING_DELETE_FAILURE',

    ME_LISTING_FIELD_CHANGED: 'ME_LISTING_FIELD_CHANGED',

    ME_LISTING_VALID_FORM_SUBMITTED: 'ME_LISTING_VALID_FORM_SUBMITTED',
    ME_LISTING_INVALID_FORM_SUBMITTED: 'ME_LISTING_INVALID_FORM_SUBMITTED'
};