export const meUserConstants = {
    ME_USER_REQUEST: 'ME_USER_REQUEST',
    ME_USER_SUCCESS: 'ME_USER_SUCCESS',
    ME_USER_FAILURE: 'ME_USER_FAILURE',

    ME_USER_INSERT_REQUEST: 'ME_USER_INSERT_REQUEST',
    ME_USER_INSERT_SUCCESS: 'ME_USER_INSERT_SUCCESS',
    ME_USER_INSERT_FAILURE: 'ME_USER_INSERT_FAILURE',

    ME_USER_UPDATE_REQUEST: 'ME_USER_UPDATE_REQUEST',
    ME_USER_UPDATE_SUCCESS: 'ME_USER_UPDATE_SUCCESS',
    ME_USER_UPDATE_FAILURE: 'ME_USER_UPDATE_FAILURE',

    ME_USER_FIELD_CHANGED: 'ME_USER_FIELD_CHANGED',

    ME_USER_VALID_FORM_SUBMITTED: 'ME_USER_VALID_FORM_SUBMITTED',
    ME_USER_INVALID_FORM_SUBMITTED: 'ME_USER_INVALID_FORM_SUBMITTED'
};
