export const searchConstants = {
    GET_SEARCH_FILTERS: 'GET_SEARCH_FILTERS',
    
    SEARCH_LISTING_REQUEST: 'ME_LISTING_REQUEST',
    SEARCH_LISTING_SUCCESS: 'ME_LISTING_SUCCESS',
    SEARCH_LISTING_FAILURE: 'ME_LISTING_FAILURE',

    SEARCH_CITY_REQUEST: 'SEARCH_CITY_REQUEST',
    SEARCH_CITY_SUCCESS: 'SEARCH_CITY_SUCCESS',
    SEARCH_CITY_FAILURE: 'SEARCH_CITY_FAILURE',

    FILTERS_CHANGED: 'FILTERS_CHANGED'
}