export const signupConstants = {
    SIGNUP_REQUEST: 'SIGNUP_REQUEST',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
    SIGNUP_FAILURE: 'SIGNUP_FAILURE',

    SIGNUP_FIELD_CHANGED: 'SIGNUP_FIELD_CHANGED',
    SIGNUP_INVALID_FORM_SUBMITTED: 'SIGNUP_INVALID_FORM_SUBMITTED'
}