export const territoryConstants = {
    TERRITORY_REQUEST: 'TERRITORY_REQUEST',
    TERRITORY_SUCCESS: 'TERRITORY_SUCCESS',
    TERRITORY_FAILURE: 'TERRITORY_FAILURE',

    TERRITORY_COUNTRY_REQUEST: 'TERRITORY_COUNTRY_REQUEST',
    TERRITORY_COUNTRY_SUCCESS: 'TERRITORY_COUNTRY_SUCCESS',
    TERRITORY_COUNTRY_FAILURE: 'TERRITORY_COUNTRY_FAILURE',
    
    TERRITORY_PROVINCE_REQUEST: 'TERRITORY_PROVINCE_REQUEST',
    TERRITORY_PROVINCE_SUCCESS: 'TERRITORY_PROVINCE_SUCCESS',
    TERRITORY_PROVINCE_FAILURE: 'TERRITORY_PROVINCE_FAILURE',
   
    TERRITORY_REGION_REQUEST: 'TERRITORY_REGION_REQUEST',
    TERRITORY_REGION_SUCCESS: 'TERRITORY_REGION_SUCCESS',
    TERRITORY_REGION_FAILURE: 'TERRITORY_REGION_FAILURE',
    
    TERRITORY_TOWN_REQUEST: 'TERRITORY_TOWN_REQUEST',
    TERRITORY_TOWN_SUCCESS: 'TERRITORY_TOWN_SUCCESS',
    TERRITORY_TOWN_FAILURE: 'TERRITORY_TOWN_FAILURE'
}